<script lang="ts">
	import { app } from '$lib/state.svelte';
	import SourceList from '$lib/components/SourceList.svelte';
	import Button from '$lib/ui/Button.svelte';
	import Chip from '$lib/ui/Chip.svelte';
	import Input from '$lib/ui/Input.svelte';
	import {
		BASIS_COLOR,
		BASIS_SHORT,
		LAYER_COLOR,
		ds,
		institutionById,
		meetsBasis,
		overlaps,
		personById,
		relKind,
		relationshipsByEntity,
		type Basis,
		type Layer
	} from '$lib/model';
	import { describeInterval, durationLabel, nameOf, entityName, relLabel, t } from '$lib/t.svelte';
	import { format } from '$lib/i18n';

	/**
	 * Structured investigative search.
	 *
	 * The important design constraint: answers are computed by traversing the dataset,
	 * not generated by a language model. Every row is a record with sources attached.
	 * An AI layer can sit on top of this later to phrase the question, but it must not
	 * be what produces the answer, or the whole evidentiary architecture is decorative.
	 */

	type Mode = 'officeholders' | 'crossings' | 'connections';

	let mode = $state<Mode>('officeholders');
	let instFilter = $state<string[]>(['ministry-interior']);
	let layerFilter = $state<Layer | 'all'>('all');
	let fromYear = $state(1987);
	let toYear = $state(2011);
	let setA = $state<string[]>(['armed-forces', 'military-security']);
	let setB = $state<string[]>(['presidential-security', 'presidency']);
	let subject = $state('ben-ali');
	let instQuery = $state('');
	let setAQuery = $state('');
	let setBQuery = $state('');

	const institutions = $derived([...ds.institutions].sort((a, b) => a.order - b.order));

	function matchesFilter(inst: (typeof institutions)[number], q: string): boolean {
		const needle = q.trim().toLowerCase();
		if (!needle) return true;
		const hay = `${nameOf(inst)} ${inst.abbr ?? ''}`.toLowerCase();
		return hay.includes(needle);
	}

	const filteredInst = $derived(institutions.filter((i) => matchesFilter(i, instQuery)));
	const filteredSetA = $derived(institutions.filter((i) => matchesFilter(i, setAQuery)));
	const filteredSetB = $derived(institutions.filter((i) => matchesFilter(i, setBQuery)));

	const range = $derived<[number, number]>([
		Date.UTC(Math.min(fromYear, toYear), 0, 1),
		Date.UTC(Math.max(fromYear, toYear), 11, 31)
	]);

	const eligible = $derived(
		ds.positions.filter(
			(p) =>
				meetsBasis(p.basis as Basis, app.basisFloor) &&
				app.activeLayers.has(p.layer as Layer) &&
				(layerFilter === 'all' || p.layer === layerFilter)
		)
	);

	// --- Query 1: officeholders in an institution within a window --------------

	const officeholders = $derived.by(() => {
		const rows = eligible.filter(
			(p) =>
				(instFilter.length === 0 || instFilter.includes(p.institution)) &&
				overlaps(p.interval, range[0], range[1])
		);
		return rows.sort(
			(a, b) => b.authority - a.authority || a.interval.startEarliest - b.interval.startEarliest
		);
	});

	// --- Query 2: people who served in BOTH sets ------------------------------
	//
	// This is the query that finds bridge figures, and it is the one the underlying
	// research kept reaching for by hand.

	const crossings = $derived.by(() => {
		const inA = new Map<string, typeof eligible>();
		const inB = new Map<string, typeof eligible>();
		for (const p of eligible) {
			if (!overlaps(p.interval, range[0], range[1])) continue;
			if (setA.includes(p.institution)) {
				inA.set(p.holder, [...(inA.get(p.holder) ?? []), p]);
			}
			if (setB.includes(p.institution)) {
				inB.set(p.holder, [...(inB.get(p.holder) ?? []), p]);
			}
		}
		const both = [...inA.keys()].filter((id) => inB.has(id));
		return both
			.map((id) => ({
				id,
				a: inA.get(id)!,
				b: inB.get(id)!,
				years: [...inA.get(id)!, ...inB.get(id)!].reduce((s, p) => s + p.years, 0)
			}))
			.sort((x, y) => y.years - x.years);
	});

	// --- Query 3: everything connected to one entity in a window --------------

	const connections = $derived.by(() => {
		const rels = (relationshipsByEntity.get(subject) ?? []).filter(
			(r) =>
				meetsBasis(r.basis as Basis, app.basisFloor) &&
				(r.interval.raw.start === null || overlaps(r.interval, range[0], range[1]))
		);
		const posts = eligible.filter(
			(p) => p.holder === subject && overlaps(p.interval, range[0], range[1])
		);
		return { rels, posts };
	});

	const PRESETS: { label: string; run: () => void }[] = [
		{
			label: t('investigate.preset.1'),
			run: () => {
				mode = 'officeholders';
				instFilter = ['ministry-interior', 'national-security', 'national-guard'];
				fromYear = 1987;
				toYear = 2011;
				layerFilter = 'all';
			}
		},
		{
			label: t('investigate.preset.2'),
			run: () => {
				mode = 'crossings';
				setA = ['armed-forces', 'land-forces', 'navy', 'air-force', 'military-security', 'anrsd'];
				setB = ['presidency', 'presidential-security', 'presidential-security-adviser'];
				fromYear = 1956;
				toYear = 2026;
			}
		},
		{
			label: t('investigate.preset.3'),
			run: () => {
				mode = 'crossings';
				setA = ['mabrouk-group', 'elloumi-group', 'nessma-tv', 'biat', 'trabelsi-network'];
				setB = ['head-of-government', 'presidency', 'nidaa-tounes', 'qalb-tounes'];
				fromYear = 1987;
				toYear = 2026;
			}
		},
		{
			label: t('investigate.preset.4'),
			run: () => {
				mode = 'officeholders';
				instFilter = ['national-security', 'national-guard', 'ministry-interior'];
				fromYear = 2021;
				toYear = 2026;
			}
		},
		{
			label: t('investigate.preset.5'),
			run: () => {
				mode = 'connections';
				subject = 'ben-ali';
				fromYear = 1956;
				toYear = 2026;
			}
		}
	];

	function toggle(list: string[], id: string): string[] {
		return list.includes(id) ? list.filter((x) => x !== id) : [...list, id];
	}
</script>

<svelte:head>
	<title>Investigate · DeepTunisia</title>
	<meta
		name="description"
		content="Structured queries over the Tunisian power graph. Answers are computed from source-backed records, not generated by a language model."
	/>
</svelte:head>

<div class="page">
	<div class="toolbar">
		<span class="eyebrow">{t('investigate.eyebrow')}</span>
		<p class="hint">{t('investigate.hint')}</p>
	</div>

	<div class="presets">
		{#each PRESETS as p (p.label)}
			<Button variant="outline" size="xs" onclick={p.run}>{p.label}</Button>
		{/each}
	</div>

	<div class="builder">
		<div class="modes">
			<Button variant="outline" size="xs" active={mode === 'officeholders'} onclick={() => (mode = 'officeholders')}
				>{t('investigate.officeholders')}</Button
			>
			<Button variant="outline" size="xs" active={mode === 'crossings'} onclick={() => (mode = 'crossings')}
				>{t('investigate.both')}</Button
			>
			<Button variant="outline" size="xs" active={mode === 'connections'} onclick={() => (mode = 'connections')}
				>{t('investigate.connected')}</Button
			>
		</div>

		<div class="period">
			<label>
				<span>{t('investigate.from')}</span>
				<input type="number" min="1956" max="2026" bind:value={fromYear} />
			</label>
			<label>
				<span>{t('investigate.to')}</span>
				<input type="number" min="1956" max="2026" bind:value={toYear} />
			</label>
		</div>

		{#if mode === 'officeholders'}
			<fieldset>
				<legend>{t('investigate.institutions')} <span class="mono">{instFilter.length || 'any'}</span></legend>
				<div class="filter-row">
					<Input bind:value={instQuery} placeholder={t('ctl.search')} size="xs" />
				</div>
<div class="chips">
					{#each filteredInst as i (i.id)}
						<Button
							variant="outline"
							size="xs"
							active={instFilter.includes(i.id)}
							tint={LAYER_COLOR[i.layer as Layer]}
							onclick={() => (instFilter = toggle(instFilter, i.id))}>{i.abbr ?? nameOf(i)}</Button
						>
					{/each}
				</div>
			</fieldset>
		{:else if mode === 'crossings'}
			<div class="two-sets">
				<fieldset>
					<legend>{t('investigate.setA')} <span class="mono">{setA.length}</span></legend>
					<div class="filter-row">
						<Input bind:value={setAQuery} placeholder={t('ctl.search')} size="xs" />
					</div>
					<div class="chips">
						{#each filteredSetA as i (i.id)}
							<Button
								variant="outline"
								size="xs"
								active={setA.includes(i.id)}
								tint={LAYER_COLOR[i.layer as Layer]}
								onclick={() => (setA = toggle(setA, i.id))}>{i.abbr ?? nameOf(i)}</Button
							>
						{/each}
					</div>
				</fieldset>
				<fieldset>
					<legend>{t('investigate.setB')} <span class="mono">{setB.length}</span></legend>
					<div class="filter-row">
						<Input bind:value={setBQuery} placeholder={t('ctl.search')} size="xs" />
					</div>
					<div class="chips">
						{#each filteredSetB as i (i.id)}
							<Button
								variant="outline"
								size="xs"
								active={setB.includes(i.id)}
								tint={LAYER_COLOR[i.layer as Layer]}
								onclick={() => (setB = toggle(setB, i.id))}>{i.abbr ?? nameOf(i)}</Button
							>
						{/each}
					</div>
				</fieldset>
			</div>
		{:else}
			<fieldset>
				<legend>{t('investigate.subject')}</legend>
				<select bind:value={subject}>
					{#each [...ds.people].sort((a, b) => nameOf(a).localeCompare(nameOf(b))) as p (p.id)}
						<option value={p.id}>{nameOf(p)}</option>
					{/each}
					{#each institutions as i (i.id)}
						<option value={i.id}>{nameOf(i)}</option>
					{/each}
				</select>
			</fieldset>
		{/if}
	</div>

	<div class="results">
		{#if mode === 'officeholders'}
			<h2>
				{format(app.locale, 'investigate.holdersCount', {
					n: officeholders.length,
					from: Math.min(fromYear, toYear),
					to: Math.max(fromYear, toYear)
				})}
			</h2>
			{#if officeholders.length === 0}
				<p class="empty">{t('investigate.empty')}</p>
			{:else}
				<table>
					<thead>
						<tr>
							<th>{t('investigate.person')}</th><th>{t('investigate.post')}</th><th>{t('investigate.institution')}</th><th>{t('investigate.span')}</th><th class="num">{t('investigate.held')}</th
							><th>{t('investigate.basis')}</th>
						</tr>
					</thead>
					<tbody>
						{#each officeholders as p (p.id)}
							<tr>
								<td class="who">
									<button onclick={() => app.select(p.holder)}>{entityName(p.holder)}</button>
								</td>
								<td>{p.roleTitle}</td>
								<td class="inst">{nameOf(institutionById.get(p.institution))}</td>
								<td class="span mono">{describeInterval(p.interval)}</td>
								<td class="num mono">{durationLabel(p.years)}</td>
								<td>
									<Chip size="xs" tint={BASIS_COLOR[p.basis as Basis]}>{BASIS_SHORT[p.basis as Basis]}</Chip>
								</td>
							</tr>
						{/each}
					</tbody>
				</table>
			{/if}
		{:else if mode === 'crossings'}
			<h2>{format(app.locale, 'investigate.crossingsCount', { n: crossings.length })}</h2>
			<p class="note">{t('investigate.crossNote')}</p>
			{#if crossings.length === 0}
				<p class="empty">{t('investigate.crossEmpty')}</p>
			{:else}
				<div class="cross-list">
					{#each crossings as c (c.id)}
						<article>
							<header>
								<button class="cname" onclick={() => app.select(c.id)}>{entityName(c.id)}</button>
								<span class="mono ctotal">{durationLabel(c.years)} {t('investigate.total')}</span>
							</header>
							<div class="two">
								<div>
									<span class="eyebrow">{t('investigate.setA')}</span>
									<ul>
										{#each c.a as p (p.id)}
											<li>
												<strong>{p.roleTitle}</strong>
												<span class="mono">{describeInterval(p.interval)}</span>
												<SourceList ids={p.sources} compact />
											</li>
										{/each}
									</ul>
								</div>
								<div>
									<span class="eyebrow">{t('investigate.setB')}</span>
									<ul>
										{#each c.b as p (p.id)}
											<li>
												<strong>{p.roleTitle}</strong>
												<span class="mono">{describeInterval(p.interval)}</span>
												<SourceList ids={p.sources} compact />
											</li>
										{/each}
									</ul>
								</div>
							</div>
						</article>
					{/each}
				</div>
			{/if}
		{:else}
			<h2>{format(app.locale, 'investigate.connCount', { name: entityName(subject), n: connections.rels.length, m: connections.posts.length })}</h2>
			{#if connections.posts.length}
				<h3>{t('investigate.postsInPeriod')}</h3>
				<ul class="plain">
					{#each connections.posts as p (p.id)}
						<li>
							<strong>{p.roleTitle}</strong>
							<span class="mono">{describeInterval(p.interval)}</span>
							<Chip size="xs" tint={BASIS_COLOR[p.basis as Basis]}>{BASIS_SHORT[p.basis as Basis]}</Chip>
						</li>
					{/each}
				</ul>
			{/if}
			{#if connections.rels.length}
				<h3>{t('investigate.connections')}</h3>
				<ul class="plain">
					{#each connections.rels as r (r.id)}
						{@const other = r.from === subject ? r.to : r.from}
						<li>
							<button onclick={() => app.select(other)}>{entityName(other)}</button>
							<span class="rtype">{relLabel(r.type)}</span>
							<Chip size="xs" tint={BASIS_COLOR[r.basis as Basis]}>{BASIS_SHORT[r.basis as Basis]}</Chip>
							{#if relKind(r.type) !== 'documented' && r.attributed_to}
								<span class="attrib">{format(app.locale, 'investigate.claimedBy', { who: r.attributed_to })}</span>
							{/if}
							<p class="rdesc">{r.description}</p>
							<SourceList ids={r.sources} compact />
						</li>
					{/each}
				</ul>
			{/if}
		{/if}
	</div>
</div>

<style>
	.page {
		flex: 1;
		overflow-y: auto;
		padding: 0 0 70px;
	}
	.toolbar {
		display: flex;
		align-items: center;
		gap: var(--s-6);
		padding: var(--s-4) var(--s-6);
		border-bottom: 1px solid var(--border-subtle);
		flex-wrap: wrap;
	}
	.hint {
		margin: 0;
		font-size: var(--t-sm);
		line-height: var(--lh-snug);
		color: var(--text-secondary);
		max-width: 68ch;
	}

	.presets {
		display: flex;
		gap: var(--s-2);
		flex-wrap: wrap;
		padding: var(--s-5) var(--s-6);
		border-bottom: 1px solid var(--border-subtle);
	}
	.builder {
		padding: var(--s-5) var(--s-6);
		border-bottom: 1px solid var(--border-subtle);
		background: var(--surface-raised);
		display: flex;
		flex-direction: column;
		gap: var(--s-5);
	}
	.modes {
		display: flex;
		gap: 3px;
	}
	.period {
		display: flex;
		gap: 14px;
	}
	.period label {
		display: flex;
		align-items: center;
		gap: 6px;
		font-size: 11px;
		color: var(--text-secondary);
	}
	input[type='number'] {
		width: 74px;
		font-family: var(--font-mono);
		font-size: 12px;
		background: var(--surface-sunken);
		border: 1px solid var(--border-default);
		border-radius: var(--r-sm);
		color: var(--text-primary);
		padding: 3px 6px;
	}
	select {
		font: inherit;
		font-size: 12.5px;
		background: var(--surface-sunken);
		border: 1px solid var(--border-default);
		border-radius: var(--r-sm);
		color: var(--text-primary);
		padding: 4px 7px;
		max-width: 320px;
	}

	fieldset {
		border: none;
		padding: 0;
		margin: 0;
		min-width: 0;
	}
	legend {
		font-family: var(--font-mono);
		font-size: 10px;
		letter-spacing: 0.1em;
		text-transform: uppercase;
		color: var(--text-faint);
		padding: 0 0 6px;
	}
	.two-sets {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 18px;
	}
	.filter-row {
		max-width: 320px;
		margin-block-end: var(--s-3);
	}
	.chips {
		display: flex;
		flex-wrap: wrap;
		gap: 3px;
	}
	.results {
		padding: var(--s-6) var(--s-6) 0;
	}
	.results h2 {
		font-family: var(--font-serif);
		font-size: var(--t-lg);
		font-weight: 550;
		margin-bottom: var(--s-4);
		letter-spacing: var(--track-tight);
	}
	.results h3 {
		font-size: var(--t-xs);
		font-family: var(--font-mono);
		letter-spacing: var(--track-caps);
		text-transform: uppercase;
		color: var(--text-faint);
		margin: var(--s-7) 0 var(--s-4);
	}
	.note {
		margin: 0 0 var(--s-5);
		font-size: var(--t-sm);
		line-height: var(--lh-snug);
		color: var(--text-secondary);
		max-width: 86ch;
	}
	.empty {
		font-size: var(--t-md);
		line-height: var(--lh-snug);
		color: var(--text-secondary);
		max-width: 60ch;
		padding: var(--s-6) 0;
	}

	table {
		width: 100%;
		border-collapse: collapse;
		font-size: 12.5px;
	}
	th {
		text-align: start;
		font-weight: 400;
		font-size: 10px;
		text-transform: uppercase;
		letter-spacing: 0.07em;
		color: var(--text-faint);
		padding: 6px 12px 6px 0;
		border-bottom: 1px solid var(--border-default);
	}
	td {
		padding: 5px 12px 5px 0;
		border-bottom: 1px solid color-mix(in srgb, var(--border-subtle) 55%, transparent);
		vertical-align: top;
	}
	th.num,
	td.num {
		text-align: end;
	}
	.who button {
		font-weight: 500;
		text-decoration: underline;
		text-decoration-color: var(--border-default);
	}
	.who button:hover {
		text-decoration-color: var(--accent);
	}
	.inst,
	.span {
		color: var(--text-secondary);
	}
	.span {
		font-size: 10.5px;
	}

	.cross-list {
		display: flex;
		flex-direction: column;
		gap: 12px;
		max-width: 1100px;
	}
	.cross-list article {
		border: 1px solid var(--border-subtle);
		border-inline-start: 3px solid var(--accent);
		border-radius: var(--r-md);
		padding: 12px 14px;
		background: var(--surface-raised);
	}
	.cross-list header {
		display: flex;
		align-items: baseline;
		gap: 10px;
		margin-bottom: 10px;
	}
	.cname {
		font-size: 14px;
		font-weight: 500;
		text-decoration: underline;
		text-decoration-color: var(--border-default);
	}
	.ctotal {
		font-size: 10.5px;
		color: var(--text-faint);
	}
	.two {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 18px;
	}
	.two ul,
	ul.plain {
		list-style: none;
		margin: 4px 0 0;
		padding: 0;
		display: flex;
		flex-direction: column;
		gap: 9px;
	}
	.two li,
	ul.plain li {
		font-size: 12px;
	}
	.two li strong,
	ul.plain li strong {
		display: block;
		font-weight: 500;
	}
	.two li .mono,
	ul.plain li .mono {
		font-size: 10.5px;
		color: var(--accent);
	}
	ul.plain li {
		border-bottom: 1px solid color-mix(in srgb, var(--border-subtle) 55%, transparent);
		padding-bottom: 9px;
	}
	ul.plain button {
		font-weight: 500;
		text-decoration: underline;
		text-decoration-color: var(--border-default);
	}
	.rtype {
		font-size: 10px;
		text-transform: uppercase;
		letter-spacing: 0.06em;
		color: var(--text-faint);
		margin: 0 6px;
	}
	.attrib {
		font-size: 10px;
		font-family: var(--font-mono);
		color: var(--basis-inferred);
	}
	.rdesc {
		margin: 4px 0 5px;
		font-size: 11.5px;
		color: var(--text-secondary);
		line-height: 1.5;
	}

	@media (max-width: 900px) {
		.two-sets,
		.two {
			grid-template-columns: 1fr;
		}
	}
</style>
